### ISSUE TITLE
Fix unit tests for GitHub actions

### ISSUE THREAD

**Issue by danitseitlin** [danitseitlin/package-deployer#130]

**Comment by danitseitlin** [comment]
(node:1651) UnhandledPromiseRejectionWarning: Error: Mising input "npm_access_token"
    at verifyInputs (/home/runner/work/package-deployer/package-deployer/dist/index.js:586:19)
    at /home/runner/work/package-deployer/package-deployer/dist/index.js:615:9
    at Object.191 (/home/runner/work/package-deployer/package-deployer/dist/index.js:621:3)
    at __webpack_require__ (/home/runner/work/package-deployer/package-deployer/dist/index.js:24:31)
    at startup (/home/runner/work/package-deployer/package-deployer/dist/index.js:43:19)
    at /home/runner/work/package-deployer/package-deployer/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/package-deployer/package-deployer/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
(node:1651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1651) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
